version: '3.8'
services:
  stat-service:
    build: ./ewm-stat-service
    container_name: ewm-stat-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  stats-db:
    image: postgres:15-alpine
    container_name: stats-db-container-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-main-service:
    build: ./ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stat-service
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5431/ewm-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-db:
    image: postgres:15-alpine
    container_name: ewm-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6540:5431"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin