    CREATE TABLE IF NOT EXISTS users(
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                email VARCHAR(255) NOT NULL,
                                name VARCHAR(255) NOT NULL,
                                CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);